STAGE: production
AWS_REGION: ap-southeast-1
ACCOUNT_ID: 146532827265
LOG_LEVEL: debug

SECURITY_GROUP_ID: sg-0730641d8f043d9b5
SUBNETID_1: subnet-0c9e1d895f42f3a43
SUBNETID_2: subnet-0d9497e68fb0a8077
NODE_ENV: production

TZ:
DB_PASSWORD:
NODE_NO_WARNINGS:
KMS_RETRYTIME:
DEPLOY_ROLE: 





